### ISSUE TITLE
Make project read gzipped genotype files. 

### ISSUE THREAD

**Issue by timknut** [haraldgrove/snptranslate#6]
Hi! 
We are now possibly including `snptranslate` in https://github.com/timknut/geno_imputation. There are however many files to convert, and we would want to keep them gzipped. 

I thought about implementing a test in the ioMODS for .gz endings, and use:
```python
with gzip.open(input,'r') as fin:
            for line in fin:
```
or
```python
with open(input,'r') as fin:
            for line in fin:
```
based on:
```python
def check_fileending(input):
        """
        Determines if input file ends in .gz
        """
        if input.lower().endswith(('.gz')):
                return True
```

Can you point to a sensible way of implementing this? 
In R I would let the check return a read function based on ifelse, but I cannot see how this can be done with the `with open(input) as fin:` syntax. 

Or will it be too much work? 

Tim

**Comment by haraldgrove** [comment]
One method I've already used elsewhere is:

```
if check_fileending(input_file): # isgzip would probably be a better name
    op = gzip.open
else:
    op = open
with op(input_file,'r') as fin:
```

**Comment by haraldgrove** [comment]
Just in case I maybe should have explained a bit more. In python you can assign methods to object names in the same way as with numbers, lists, etc.

I just tested a bit with writing gzip files, and for some reason it didn't quite work. You're free to tackle that issue if you want.

**Comment by timknut** [comment]
Ah, brilliant! Just what I needed.

Writing gzip is not crucial. plink text format is only temporary. Genotypes
will be stored as raw-data and plink binary.

Tim

On 12 July 2016 at 13:02, Harald Grove <notifications@github.com> wrote:

> Just in case I maybe should have explained a bit more. In python you can
> assign methods to object names in the same way as with numbers, lists, etc.
>
> I just tested a bit with writing gzip files, and for some reason it didn't
> quite work. You're free to tackle that issue if you want.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/haraldgrove/snptranslate/issues/6#issuecomment-232007721>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFiStv2VRJ15aACF6I607jL32R8XE4C1ks5qU3Q3gaJpZM4JKNZH>
> .
>



-- 
mvh

Tim Knutsen

**Comment by timknut** [comment]
#8 Fixed.
